### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ryanmeinzer** [learn-co-curriculum/programming-univbasics-intro-to-programming-as-conversation#3]
"We've designed our curriculum to not to that." has a typo. Should be "We've designed our curriculum to not do that."

**Comment by maxwellbenton** [comment]
Hi @ryanmeinzer,

Thank you for spotting this and providing feedback. We've corrected this typo, which should resolve this issue.

Thank you for contributing to a Learn lesson!
