### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ryanmeinzer** [learn-co-curriculum/programming-univbasics-intro-to-programming-as-conversation#4]
"Conversation" comes from the Latin words mean "by taking turns." Should be "Conversation" comes from the Latin word meaning "by taking turns."

**Comment by maxwellbenton** [comment]
Hi @ryanmeinzer,

Thank you for spotting this and providing feedback. We've corrected this typo, which should resolve this issue.

Thank you for contributing to a Learn lesson!
